Task 5 1
ymazhar/node-js-lab pull request #5
Opened 2022-07-22 13:32 UTC by ymazhar

2022-07-23 13:50 UTC, BorysLypivets requested changes

2022-07-23 13:50 UTC, BorysLypivets commented on src/api/group/group-router.js
> +groupRouter.post('/', asyncHandler(groupSchema), createGroupController);
Need to make few changes:

1. Please, change current line to 
```groupRouter.post('/', createGroupController);```
2. Please go to ```./controllers/group.controller.js``` and change ```createGroupcontroller``` definition to 
`const createGroupController = asyncHandler('Create - Group - Controller', groupSchema, async () => {
... your current handler here
});`
3. remove unused imports of asyncHandler and groupSchema from ```src/api/group/group-router.js```
4. need to do the same for all endpoints in the project

2022-07-23 13:50 UTC, BorysLypivets commented on src/api/user/controllers/user.controller.js
> +export async function createUserController(req) {
please apply changes that described for `src/api/group/group-router.js` for current file

2022-07-23 13:50 UTC, BorysLypivets commented on src/api/user/controllers/user.controller.js
> +    try {
Please remove this try/catch - errors should be handled in your error middleware (need to do the same for all controller handler)

After you applied changes described in the `src/api/group/group-router.js`
you don't need try/catch here, you already have handler().catch() inside asyncHandler function.

2022-07-23 13:50 UTC, BorysLypivets commented on src/api/user/user-router.js
> +userRouter.get('/autosuggest?', asyncHandler(userAutoSuggestionSchema, getAutoSuggestUsersController));
please use approach described for `src/api/group/group-router.js`

I mean, you should not call asyncHandler inside router files, please move it to controller file

2022-07-23 13:50 UTC, BorysLypivets commented on src/middleware/asynchandler.midleware.js
> +                return next(new SchemaValidationFailedError('Request Body is not valid'));
Front End should know which field of the payload failed validation, 
as possible solution your could pass joi error as field of the `SchemaValidationFailedError`

2022-07-23 13:50 UTC, BorysLypivets commented on src/middleware/error.middleware.js
> +export class CustomError extends Error {
please move definition of Errors to separate file src/lib/error.js

2022-07-23 13:50 UTC, BorysLypivets commented on src/middleware/error.middleware.js
> +export const HttpStatusCode = {
please move definition of status code to separate file src/lib/status.js

2022-07-23 13:50 UTC, BorysLypivets commented on src/middleware/logger.middleware.js
> +import { transports, format, createLogger } from 'winston';
Please move this file to src/lib/logger.js 
This file doesn't contain any middleware so it should not be in `middleware` folder

2022-07-23 13:50 UTC, BorysLypivets commented on src/middleware/asynchandler.midleware.js
> +import { SchemaValidationFailedError } from './error.middleware.js';
please fix filename asynchandler.mi**d**leware.js -> async-handler.mi**dd**leware.js

2022-07-23 13:50 UTC, BorysLypivets commented on src/server.js
>      try {
please add `process.on('uncaughtException', ....) ` (Task 5.2 in home work)
on error your should log the exception in with logger and exit process

after your have `process.on('uncaughtException', ....) ` you probably don't need this try/catch any more 
(please check it before your commit changes =) )

2022-07-23 13:50 UTC, BorysLypivets commented on src/server.js
> +            throw error;
please, change handler to log error, do not throw them from handler

2022-07-23 13:50 UTC, BorysLypivets commented on src/server.js
>          app.use('/', rootRouter);
look like we missed Task 5.1 on our discussion.

please add one more middleware before `app.use('/', rootRouter);`
this middleware should:
1. use logger to log request that came to app 
2. use `response.on('finish', () => {})` to add handler for response to log response after it finished

2022-07-23 20:02 UTC, BorysLypivets requested changes

2022-07-24 18:39 UTC, ymazhar commented on src/api/group/service/group.service.js
> +        return new GroupNotExistError(`Cannot find a group with exist id: ${id}`);
Fixed

2022-07-25 08:01 UTC, BorysLypivets requested changes

2022-07-25 08:01 UTC, BorysLypivets commented on src/api/user/service/user.service.js
> +        return new UserNotExistError(`Can't find user with id: ${id}`);
please, change `return new` to `throw new`  (1/2)

2022-07-25 08:01 UTC, BorysLypivets commented on src/api/user/service/user.service.js
> +        return new UserLoginExistError(`${data.login} login already exist`);
please, change `return new` to `throw new` (2/2)

2022-07-26 08:48 UTC, BorysLypivets approved these changes

2022-07-26 09:11 UTC, merged