Task 6 1
ymazhar/node-js-lab pull request #6
Opened 2022-08-04 14:26 UTC by ymazhar

2022-08-04 16:55 UTC, BorysLypivets requested changes

2022-08-04 16:55 UTC, BorysLypivets commented on src/lib/async-handler.js
> +        return await handler(trx);
in these two lines you shouldn't write **await** after **return**.

async function always returns promise, in case you return something that is not a promise, async function wrap it in a promise automatically.
"...So, async ensures that the function returns a promise, and wraps non-promises in it. Simple enough, right? ..."
https://javascript.info/async-await

Please, remove **await** from these two lines.

2022-08-07 07:35 UTC, ymazhar commented on src/lib/async-handler.js
> +        return await handler(trx);
Thank you, fixed.

2022-08-07 07:35 UTC, ymazhar commented on src/api/auth-router.js
> +// import jwt from 'jsonwebtoken';
Thank you, fixed.

2022-08-07 07:38 UTC, ymazhar commented on src/api/user/service/user.service.js
> +        throw new UnauthorizedError(`${data.login} login already exist`);
Thank you, fixed

2022-08-08 05:56 UTC, BorysLypivets approved these changes

2022-08-09 09:25 UTC, merged