Task 7 1
ymazhar/node-js-lab pull request #7
Opened 2022-08-22 09:21 UTC by ymazhar

2022-08-23 08:43 UTC, BorysLypivets requested changes

2022-08-23 08:43 UTC, BorysLypivets commented on .gitignore
> +/package-lock.json
package-lock.json should be committed in the repo, we need it to install correct versions of dependencies via ```npm ci```

https://docs.npmjs.com/cli/v8/commands/npm-ci

2022-08-23 08:43 UTC, BorysLypivets commented on src/config/index.js
> -export default {
we don't need to remove this file, please keep it
But we need to change literal, like ```'password'``` to the process.env.SOME_VARIABLE_FROM_DOT_ENV_FILE

2022-08-23 08:43 UTC, BorysLypivets commented on src/middleware/authorization.js
> +    return jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, (error) => {
in repo, the only place where you should have access to the ```proccess.env``` object should be src/config/index.js.

please change this line to ```jwt.verify(token, config.accessToken, (error) => { ...})```

2022-08-23 14:08 UTC, ymazhar commented on .gitignore
> +/package-lock.json
Fixed

2022-08-23 14:21 UTC, ymazhar commented on src/config/index.js
> -export default {
Fixed

2022-08-23 15:25 UTC, ymazhar commented on src/middleware/authorization.js
> +    return jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, (error) => {
fixed

2022-08-24 08:22 UTC, BorysLypivets requested changes

2022-08-24 08:22 UTC, BorysLypivets commented on src/server.js
> +    app.listen(process.env.APP_PORT, () => {
please use config.PORT here
in the repo, the only place where you should have access to the proccess.env object should be src/config/index.js.

2022-08-24 08:22 UTC, BorysLypivets commented on src/utils/jwt-helpers.js
> +    return jwt.sign(user, process.env.ACCESS_TOKEN_SECRET, { expiresIn: 120 });
please use  please use config.ACCESS_TOKEN_SECRET here
in the repo, the only place where you should have access to the proccess.env object should be src/config/index.js.

2022-08-24 08:35 UTC, ymazhar commented on src/server.js
> +    app.listen(process.env.APP_PORT, () => {
fixed

2022-09-04 12:04 UTC, BorysLypivets requested changes

2022-09-04 12:04 UTC, BorysLypivets commented on src/api/user/controllers/user.conttroller.test.js
> +            'statusCode': 200
let's change using the 200 status in case to faced an error, please change it to 204 or 404

2022-09-04 13:51 UTC, ymazhar commented on src/api/group/controllers/group.controller.test.js
> +const rawUser = {
fixed

2022-09-04 13:54 UTC, ymazhar commented on src/api/group/controllers/group.controller.test.js
> +        const { json: { id } } = await mockedRequestHandler(getGroupController, { params: { id: rawGroup.id } });
fixed

2022-09-04 13:54 UTC, ymazhar commented on src/api/group/controllers/group.controller.test.js
> +    // TODO Do I need to use a transaction?
Ok

2022-09-04 14:03 UTC, ymazhar commented on src/api/group/controllers/group.controller.test.js
> +            json: expect.objectContaining({ name: 'marketing', permissions: ['UPLOAD_FILES'] }),
fixed

2022-09-04 14:03 UTC, ymazhar commented on src/api/group/service/group.service.js
> +        raw: true,
Yes )

2022-09-04 14:04 UTC, ymazhar commented on src/api/user/controllers/user.conttroller.test.js
> +    console.log(rawUserQueryValues);
removed

2022-09-04 14:25 UTC, ymazhar commented on src/api/user/controllers/user.conttroller.test.js
> +beforeAll(() => {
fixed

2022-09-04 14:26 UTC, ymazhar commented on src/api/user/controllers/user.conttroller.test.js
> +    test('Should return user by id', async () => {
fixed

2022-09-04 14:27 UTC, ymazhar commented on src/api/user/controllers/user.conttroller.test.js
> +            expect.objectContaining(
fixed

2022-09-04 14:30 UTC, ymazhar commented on src/api/user/controllers/user.conttroller.test.js
> +            'statusCode': 200
fixed

2022-09-04 16:58 UTC, BorysLypivets requested changes

2022-09-04 16:58 UTC, BorysLypivets commented on src/utils/test-helpers.js
> +import { RAW_TEST_DATA } from './test-data.js';
It is a good idea to extract data for the unit tests in a separate file, but it is common practice to call that data 'fixtures'.

1) Please, create new files `node-js-lab/src/test/fixtures/groups.js` and `node-js-lab/src/test/fixtures/users.js`
2) move user data to the `node-js-lab/src/test/fixtures/users.js` and export data from this file
3) move group data to the `node-js-lab/src/test/fixtures/groups.js` and export data from this file
4) rename all constants in fixtures files to camelCase, please do not use uppercase names for the fixtures

2022-09-04 16:58 UTC, BorysLypivets commented on src/api/group/controllers/group.controller.test.js
> +        const requestData = { params: { id }, body: { permissions: [PERMISSIONS.SHARE] } };
in case you use `id` only once. you could write it `{ params: { id: GROUP.id }, ..... }`

2022-09-04 16:58 UTC, BorysLypivets commented on src/utils/test-helpers.js
> +        await db.query(`DROP DATABASE IF EXISTS ${name};`);
I'm not sure we need to drop all DB after each test.
It looks like you only need to Delete rows that have been inserted before you start tests.
Please change this script to remove only rows that you created but not full DB. 
Or also you can TRUNCATE table.

2022-09-05 13:10 UTC, ymazhar commented on src/utils/test-helpers.js
> +import { RAW_TEST_DATA } from './test-data.js';
fixed

2022-09-06 08:19 UTC, BorysLypivets approved these changes

2022-09-06 08:27 UTC, merged